version: '3.8'

services:
  postgres:
    container_name: franko_store_postgres
    image: postgres:latest
    env_file:
      - ./src/common/envs/development.env
    ports:
      - '5432:5432'
    volumes:
      - franko_store_data:/var/lib/postgresql/data # persistent storage for PostgreSQL data

volumes:
  franko_store_data:
